version: 2.1

orbs:
  snyk: snyk/snyk@0.0.10

workflows:
  integration:
    jobs:
      - checkout_code
      - lint:
          requires:
            - checkout_code
      - test-unit:
          requires:
            - checkout_code
      - test-integration:
          requires:
            - checkout_code
      - security-scan:
          requires:
            - checkout_code
      - compile:
          requires:
            - lint
            - test-unit
            - test-integration
            - security-scan
      - hold-for-release:
          type: approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
          require:
            - compile
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
          requires:
            - compile
            - hold-for-release

jobs:
  checkout_code:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run: git fetch --tags
      - run:
          name: Fetch deps
          command: make deps
      - save_cache:
          key: repo{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/project

  lint:
    docker:
      - image: circleci/golang:1.14
    steps:
      - restore_cache:
          key: repo{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Lint
          command: make lint

  test-unit:
    docker:
      - image: circleci/golang:1.14
    steps:
      - run: echo "This is pipeline ID << pipeline.id >>"
      - run: echo "This is git tag << pipeline.git.tag >>"
      - restore_cache:
          key: repo{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Unit Tests
          command: make test-unit

  test-integration:
    docker:
      - image: circleci/golang:1.14
    steps:
      - restore_cache:
          key: repo{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Integration Tests
          command: make test-integration

  security-scan:
    docker:
      - image: circleci/golang:1.14
    steps:
      - restore_cache:
          key: repo{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - snyk/scan:
          severity-threshold: high
          fail-on-issues: false
          monitor-on-build: true

  compile:
    docker:
      - image: circleci/golang:1.14
    steps:
      - restore_cache:
          key: repo{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run: make compile-only

  release:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: make release-publish
